project:
  render:
    - "*.qmd"

website:
  title: "testing windows arm - R aarch64"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "R Analysis"
        href: r-analysis.qmd
      - text: "R Plots"
        href: r-plots.qmd
